update logger level support.

diff --git a/env/defineEnvVars b/env/defineEnvVars
--- a/env/defineEnvVars
+++ b/env/defineEnvVars
@@ -10,36 +10,11 @@ echo "Load the Env Data..."
 # This section defines the internal 
 # Not need Change unless program change.
 #-------------------------------------------------------------------------------
-export CPU_CORE=2
-
-export PROGRAM_SDK_PATH=${ENV_PATH_ROOT}/../sdk
-export PROGRAM_SUPPORT=$PROGRAM_SDK_PATH/support
-export PROGRAM_BUILD=$PROGRAM_SDK_PATH/build
-export PROGRAM_APPLICATION=$PROGRAM_SDK_PATH/application
-export PROGRAM_DOWNLOAD=$PROGRAM_SDK_PATH/download
-export PROGRAM_IMG=$PROGRAM_SDK_PATH/img
-
-#GCC compile path info
-#support old gcc to build kernel(version low, update linux kernel next)
-#arm-linux-gnueabihf-
-export OLD_GCC_PATH=$PROGRAM_SUPPORT/arm/old_compiler/bin
-export KERNEL_CC=$OLD_GCC_PATH/arm-linux-gnueabihf-
-
-#arm-none-linux-gnueabihf-
-export NEW_GCC_PATH=$PROGRAM_SUPPORT/arm/compiler/bin
-export NEW_KERNEL_CC=$NEW_GCC_PATH/arm-none-linux-gnueabihf-
-export GCC_LIB=$PROGRAM_SUPPORT/arm/compiler/arm-none-linux-gnueabihf
-
-#aarch64-none-linux-gnueabihf-
-export AARCH_GCC_PATH=${PROGRAM_SUPPORT}/aarch64/bin
-
-#Add directory to PATH
-export PATH="usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
-export PATH=$PATH:${NEW_GCC_PATH}:${OLD_GCC_PATH}:${AARCH_GCC_PATH}
-
-#build output info
+export CPU_CORE=6
+export PROGRAM_SDK_PATH="${ENV_PATH_ROOT}"/../sdk
+export PROGRAM_DOWNLOAD="${PROGRAM_SDK_PATH}"/download
+export ENV_CONFIG_FILE="${ENV_PATH_ENVIRONMENT}"/EnvConfig.mk
 export DST_PATH="/home/freedom/Desktop/Firmware"
-export ENV_CONFIG_FILE="$ENV_PATH_ENVIRONMENT/EnvConfig.mk"
 
 #-------------------------------------------------------------------------------
 # This section defines the default internal config
@@ -86,84 +61,74 @@ declare -a supportedPlatforms=($FIRMWARE_SUPPORT_PLATFORMS)
 # Only Change if need.
 #-------------------------------------------------------------------------------
 if [[ "${supportedPlatforms[0]}" == "${FIRMWARE_CURRENT_PLATFORMS}" ]]; then
-
-    #uboot infos
     export ENV_ARCH=arm
+elif [[ "${supportedPlatforms[1]}" == "${FIRMWARE_CURRENT_PLATFORMS}" ]]; then
+    export ENV_ARCH=aarch64
+else
+    echo "${redText}error platform $FIRMWARE_CURRENT_PLATFORMS not exist in list of support${defText}"
+    exit 1
+fi
 
-    export ENV_BOOT_DIR=$PROGRAM_SUPPORT/arm/uboot
-    export ENV_KERNAL_UBOOT="u-boot-imx6ull-14x14-ddr512-emmc.imx"
+#定义SDK的工具包结构
+export PROGRAM_SDK_PLATFORM_PATH="${PROGRAM_SDK_PATH}/${ENV_ARCH}"
 
-    #kernel info
-    export ENV_KERNEL_DIR=$PROGRAM_SUPPORT/arm/kernel
-    export ENV_KERNEL_ZIMAGE=$ENV_KERNEL_DIR/arch/arm/boot/zImage
-    export ENV_KERNEL_DTB=$ENV_KERNEL_DIR/arch/arm/boot/dts/imx6ull-14x14-emmc-4.3-800x480-c.dtb
+#build目录
+export PROGRAM_BUILD="${PROGRAM_SDK_PLATFORM_PATH}"/build
+export BUILD_NFS_PATH="${PROGRAM_BUILD}"/nfs_root
+export BUILD_TFTP_PATH="${PROGRAM_BUILD}"/tftp_root
 
-    #rootfs info
-    export ENV_ROOTFS_DIR=$PROGRAM_SUPPORT/arm/rootfs
+#img目录
+export PROGRAM_IMG="${PROGRAM_SDK_PLATFORM_PATH}"/img
 
-    #global install
-    export GLOBAL_INTALL=${PROGRAM_SDK_PATH}/install/arm
+#support目录
+export PROGRAM_SUPPORT="${PROGRAM_SDK_PLATFORM_PATH}"/support
+export SUPPORT_GCC_PATH="${PROGRAM_SUPPORT}"/compiler/bin
+export SUPPORT_ENV_KERNEL_DIR="${PROGRAM_SUPPORT}"/kernel
+export SUPPORT_ENV_BOOT_DIR="${PROGRAM_SUPPORT}"/uboot
+export SUPPORT_FS_BUILDROOT_DIR="${PROGRAM_SUPPORT}"/rs_buildroot
+export SUPPORT_FS_DEBAIN_DIR="${PROGRAM_SUPPORT}"/rs_debain
+export SUPPORT_FS_UBUNTU_DIR="${PROGRAM_SUPPORT}"/rs_ubuntu
 
-    #global build
-    export NFS_PATH=$PROGRAM_BUILD/nfs_root/arm
-    export TFTP_PATH=$PROGRAM_BUILD/tftp_root/arm
+#install目录
+export PROGRAM_INSTALL="${PROGRAM_SDK_PLATFORM_PATH}"/install
 
+export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
+export PATH="${PATH}":"${SUPPORT_GCC_PATH}"
+
+if [[ "${supportedPlatforms[0]}" == "${FIRMWARE_CURRENT_PLATFORMS}" ]]; then
+    export ENV_KERNAL_UBOOT=u-boot-imx6ull-14x14-ddr512-emmc.imx
+    export ENV_KERNEL_ZIMAGE="${SUPPORT_ENV_KERNEL_DIR}"/arch/arm/boot/zImage
+    export ENV_KERNEL_DTB="${SUPPORT_ENV_KERNEL_DIR}"/arch/arm/boot/dts/imx6ull-14x14-emmc-4.3-800x480-c.dtb
+    
     export APP_C_COMPILE=arm-none-linux-gnueabihf-gcc
     export APP_CC_COMPILE=arm-none-linux-gnueabihf-g++
     export APP_AR_COMPILE=arm-none-linux-gnueabihf-ar
-    export APPLICATION_BUILDOUT=$ENV_PATH_ROOT/buildout/arm
-    export PLATFORM_LINUX_PATH=${ENV_PATH_ROOT}/platform/linux-imx-lf-6.1.y-patch
-    export PLATFORM_UBOOT_PATH=${ENV_PATH_ROOT}/platform/uboot-imx-lf_v2022.04-patch
-elif [[ "${supportedPlatforms[1]}" == "${FIRMWARE_CURRENT_PLATFORMS}" ]]; then
-    
-    export ENV_ARCH=aarch64
 
-    #uboot infos
-    export ENV_BOOT_DIR=$PROGRAM_SUPPORT/aarch64/uboot
-    export ENV_KERNAL_UBOOT="u-boot-imx6ull-14x14-ddr512-emmc.imx"
+    export APPLICATION_BUILDOUT="${ENV_PATH_ROOT}"/buildout/arm
+    export PLATFORM_LINUX_PATH="${ENV_PATH_ROOT}"/platform/linux-imx-lf-6.1.y-patch
+    export PLATFORM_UBOOT_PATH="${ENV_PATH_ROOT}"/platform/uboot-imx-lf_v2022.04-patch 
 
-    #kernel info
-    export ENV_KERNEL_DIR=$PROGRAM_SUPPORT/aarch64/kernel
-    export ENV_KERNEL_ZIMAGE=$ENV_KERNEL_DIR/arch/arm/boot/zImage
-    export ENV_KERNEL_DTB=$ENV_KERNEL_DIR/arch/arm/boot/dts/imx6ull-14x14-emmc-4.3-800x480-c.dtb
-
-    #rootfs info
-    export ENV_ROOTFS_DIR=$PROGRAM_SUPPORT/aarch64/rootfs
-
-    #global install
-    export GLOBAL_INTALL=${PROGRAM_SDK_PATH}/install/aarch64
-
-    #global build
-    export NFS_PATH=$PROGRAM_BUILD/nfs_root/aarch64
-    export TFTP_PATH=$PROGRAM_BUILD/tftp_root/aarch64
-
+    export NEW_KERNEL_CC="${SUPPORT_GCC_PATH}"/arm-none-linux-gnueabihf-
+    export GCC_LIB=$PROGRAM_SUPPORT/compiler/arm-none-linux-gnueabihf
+else
     export APP_C_COMPILE=aarch64-none-linux-gnu-gcc
     export APP_CC_COMPILE=aarch64-none-linux-gnu-g++
     export APP_AR_COMPILE=aarch64-none-linux-gnu-ar
     export APPLICATION_BUILDOUT=$ENV_PATH_ROOT/buildout/aarch64
 
-else
-    echo "${redText}error platform $FIRMWARE_CURRENT_PLATFORMS not exist in list of support${defText}"
+    export NEW_KERNEL_CC=$SUPPORT_GCC_PATH/aarch64-none-linux-gnu-
+    export GCC_LIB=$PROGRAM_SUPPORT/compiler/arm-none-linux-gnueabihf
 fi
 
 #-------------------------------------------------------------------------------
 # This section defines the path for the program
 # Not need Change unless program change.
 #-------------------------------------------------------------------------------
-#kernal_mod
-export ENV_PATH_KERNAL_MOD="${ENV_PATH_ROOT}/mod"
-
-#application 
-export APP_ROOTFS=${ENV_PATH_ROOT}/rootfs
-export APP_ROOTFS_LIB=${APP_ROOTFS}/lib
-export APPLICATION_SYS=${APP_ROOTFS}/home/sys
+export APPLICATION_MOD="${ENV_PATH_ROOT}"/mod
+export APPLICATION_ROOTFS="${ENV_PATH_ROOT}"/rootfs
 export APPLICATION_THIRDPARTS=${ENV_PATH_ROOT}/thirdparts
-export APPLICATION_EMBED=${ENV_PATH_ROOT}/embed
-
-export APP_BUILD_DRIVER=${NFS_PATH}/home/sys/modules
-export ENV_BUILD=$PROGRAM_APPLICATION/build
-export ENV_BUILD_FIRMWARE=$ENV_BUILD/firmware
-export ENV_BUILD_BIN=$ENV_BUILD_FIRMWARE/bin
+export APPLICATION_EMBED="${ENV_PATH_ROOT}"/embed
+export APPLICATION_EMBED_MODUILES="${BUILD_NFS_PATH}"/home/sys/modules
 
 #-------------------------------------------------------------------------------
 # Env Vars define finish shows
